[project]
name = "eob-cli"
version = "0.1.0"
description = "A Command Line Tool to extract structured JSON data from Explanation of Benefits Files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.16.1",
]
